### ISSUE TITLE
using with new 20h1 technical preview that has hyper-v / vbs coexistence support

### ISSUE THREAD

**Issue by myusrn** [paolo-projects/auto-unlocker#12] opened 2020-04-06 03:08 UTC
I upgraded my vmware player 15.5.2 install with a working macOS 10.15 vm configuration to the new 20h1 technical preview 16.0.0-15679048 [ http://bit.ly/getworkstation-tp ] that has hyper-v / vbs coexistence support.  

This allows one to use vmware along side hyper-v dependent services like windows docker desktop container support.

I applied auto-unlocker 1.1 to this updated install, and launched %programfiles(x86)%\VMware\VMware Workstation\vmplayer.exe to start my existing macOS 10.15 vm, and things don't appear to be working as the macOS crashes during apple logo progress bar processing.

Have you done any testing with this new vmware workstation / player technical preview and if so is there a known issue or might i be experiencing what i am due to other reasons?

**Comment by lanzorg** [comment] 2020-04-06 07:28
Isn't this version currently very limited in performance? Debug mode cannot be disabled?

**Comment by paolo-projects** [comment] 2020-04-06 09:08
For now it's still a technical preview, but it would be nice to have it supported when it's eventually released. Unfortunately mine is just a C++ port of drdonk's original patch, hence I wouldn't be able to do it on my own. If anyone with the necessary knowledge shows up with a solution I'll be glad to implement it in this tool.

**Comment by myusrn** [comment] 2020-04-06 15:58
What's the github repo for drdonk's original patch and i'll open issue there?  I searched and only see https://github.com/paolo-projects/unlocker and nothing of this sort any more under https://github.com/drdonk?tab=repositories&q=unlock results.  The reason this is big is because it will allow running macOS vm in required vmware player/workstation environment while retaining ability to run hyper-v and the things we have to do there versus having to turn hyper-v hypervisorlaunchtype [ bcdedit /enum ] into auto/on state [ bcdedit /set hypervisorlaunchtype auto ] and off state [ bcdedit /set hypervisorlaunchtype off ] followed by reboots to switch between being able to operate hyper-v and vmware environments.

**Comment by paolo-projects** [comment] 2020-04-06 16:33
I can understand, I run android emulators often (they also rely on hyperv apparently) and a couple hyperv machines every now and then and it's a pain to reboot every time just to switch from vmware to a different vm.
Best place to open another issue is in the new maintainer's repo (don't remember the name but you can find it if you go in my forked repo and look at the **forked from** tag under the repo name) or in some hackintosh forum. I guess we should wait for a proper release though before someone can get to work on it

**Comment by myusrn** [comment] 2020-04-06 16:48
the origin https://github.com/drdonk/unlocker repo is gone produces 404

**Comment by paolo-projects** [comment] 2020-04-06 17:11
I meant the text under the repo name, I can see it when I go to my repositories... anyway I just checked and the new maintainer should be [theJaxon](https://github.com/theJaxon/unlocker)

**Comment by myusrn** [comment] 2020-04-06 17:25
Wondering if the text under the repo name is something you see as the owner of repo but visitors do not see. Anyway i visited https://github.com/thejaxon/unlocker and there isn't an issues tab suggesting repo is just keeping final drop of that work.

**Comment by paolo-projects** [comment] 2020-04-06 21:39
I just checked with a private navigation session and I can see it. Probably I didn't explain it well, I was talking about my forked *[unlocker](https://github.com/paolo-projects/unlocker)* repo, which I created back then from DrDonk repo to patch some broken urls before eventually moving to this one (*auto-unlocker*) which is the one I maintain. 

This one, however, is just a convenience C++ port of that one, made to allow one-click install on every machine (*actually the one click thing is true just for windows, but most of the linux users don't like one click things anyway lol*).

> Wondering if the text under the repo name is something you see as the owner of repo but visitors do not see. Anyway i visited https://github.com/thejaxon/unlocker and there isn't an issues tab suggesting repo is just keeping final drop of that work.

Well, I guess you're right, he probably won't be releasing patches for new versions. The only hope at this point is to wait for someone with experience in that field to come around.

**Comment by myusrn** [comment] 2020-04-07 00:15
Fyi, i retested removing all presence of vmware player/workstation 15.x and new 16.x technical preview and then did another clean install of 16.x player+workstation technical preview.  I then ran autounlock Unlocker.exe against that install which succeeds fine but when you then use vmplayer.exe or vmware.exe console to create a new virtual machine the "Guest operating system" dialog doesn't present a MacOS 10.x set of options so appears a different file has to be patched for things to work.

**Comment by myusrn** [comment] 2020-04-07 02:03
I tested patching this 20h1 technical preview using unlocker 3.0.3 [ https://github.com/paolo-projects/unlocker ] and it works.  When i create a new vm i see the MacOS options and booting a macOS 10.15.4 installer iso succeeds as does booting an existing macOS 10.15.4 vmware setup i had in place before moving to this new hyper-v / vbs co-existence capable vmware technical preview.   

So it would seem autounlocker perhaps needs an update to do whatever current version of unlocker 3.0.3 is doing in order to function properly against these new 20h1 technical preview installs.  Alternatively i could have done something magically different when i applied unlocker 3.0.3 using its win-install.cmd but not sure what that would be since in each case i just ran "auto-unlocker11l\Unlocker [--install ]" and "unlocker303\win-install.cmd".

**Comment by paolo-projects** [comment] 2020-04-07 14:17
I'll run some tests and dig into it

**Comment by paolo-projects** [comment] 2020-04-07 16:05
I just checked on a clean vmware player install: I ran the python tool first, uninstalled the patch, ran the c++ tool and then compared the results with a hash tool:
<table border="1" cellpadding="5"><tr bgcolor="E0E0E0">
<th>Filename
<th>MD5
<th>SHA1
<th>CRC32
<th>SHA-256
<th>SHA-512
<th>SHA-384
<th>Full Path
<th>Modified Time
<th>Created Time
<th>Entry Modified Time
<th>File Size
<th>File Version
<th>Product Version
<th>Identical
<th>Extension
<th>File Attributes
<tr><td bgcolor=#FFE8FF nowrap>vmware-vmx.exe<td bgcolor=#FFE8FF nowrap>18b47f8f1575ed0ff1d6eb8489a9c47a<td bgcolor=#FFE8FF nowrap>4cdc2690f831730e2adcb2af4e1783bda6b5372b<td bgcolor=#FFE8FF nowrap>c695d31c<td bgcolor=#FFE8FF nowrap>f5a09140bc7e4d945cb44f5f450b119573ff9cd733daf3ebdb7947c8563c2ed1<td bgcolor=#FFE8FF nowrap>963ad28dc076ab32b01267101fb2a5ce43ed246733310f7fe3c394210edf74e713a9de226ca53fcd566ef8f6126e6515bbd055c4976ffa591775ae66b9e83518<td bgcolor=#FFE8FF nowrap>4bd862f6e337435cb103771baca8508844643139aa3bb262929f660e47921732e9c753b3652d9842a79d96d5e38662d8<td bgcolor=#FFE8FF nowrap>D:\auto-unlocker\testing\good\vmware-vmx.exe<td bgcolor=#FFE8FF nowrap>07/04/2020 16:55:19<td bgcolor=#FFE8FF nowrap>07/04/2020 16:57:01<td bgcolor=#FFE8FF nowrap>07/04/2020 16:55:19<td bgcolor=#FFE8FF nowrap>16.764.376<td bgcolor=#FFE8FF nowrap>15.5.2 build-15785246<td bgcolor=#FFE8FF nowrap>15.5.2 build-15785246<td bgcolor=#FFE8FF nowrap>1<td bgcolor=#FFE8FF nowrap>exe<td bgcolor=#FFE8FF nowrap>A
<tr><td bgcolor=#FFFFE8 nowrap>vmware-vmx-debug.exe<td bgcolor=#FFFFE8 nowrap>cfab05e9b1bd4596f54dd682cba68d5e<td bgcolor=#FFFFE8 nowrap>3701628840b4167b1969d1f60af995cc0b0c7034<td bgcolor=#FFFFE8 nowrap>d8876ee6<td bgcolor=#FFFFE8 nowrap>cf3551659b977063c69ed9499143a7f6b0ccb591720e47b65eca52f628da9b69<td bgcolor=#FFFFE8 nowrap>fd3786bd748ff02409a4b8d8257db6ab6e4854170ccf16ead94bbb0ae37db1d9a0c765c24aa8fa149318aff978f81b7180af8f4f6a1e21789f8c9a80fec02802<td bgcolor=#FFFFE8 nowrap>99e6e6ed4596c97f36891555c089a1fc7fc7aa2d9dbd903d3328ab0bae8192d5afc55aa464c4e29cb6e8c5ee471e072d<td bgcolor=#FFFFE8 nowrap>D:\auto-unlocker\testing\good\vmware-vmx-debug.exe<td bgcolor=#FFFFE8 nowrap>07/04/2020 16:55:19<td bgcolor=#FFFFE8 nowrap>07/04/2020 16:57:01<td bgcolor=#FFFFE8 nowrap>07/04/2020 16:55:19<td bgcolor=#FFFFE8 nowrap>22.104.536<td bgcolor=#FFFFE8 nowrap>15.5.2 build-15785246<td bgcolor=#FFFFE8 nowrap>15.5.2 build-15785246<td bgcolor=#FFFFE8 nowrap>2<td bgcolor=#FFFFE8 nowrap>exe<td bgcolor=#FFFFE8 nowrap>A
<tr><td bgcolor=#E8FFFF nowrap>vmwarebase.dll<td bgcolor=#E8FFFF nowrap>e8bf8ca0bb7e6f1b929ebd2777f33a22<td bgcolor=#E8FFFF nowrap>87818a402b871670f568889c8acadbf731a6ecff<td bgcolor=#E8FFFF nowrap>f73f2fcc<td bgcolor=#E8FFFF nowrap>cead472605eddca069f39157b6812c5cfd5a22e5aad04f905779981c0dfca552<td bgcolor=#E8FFFF nowrap>05f57a26d9bcc5172686693123f7199416891bc4b7de17304afd96309506712bc1ca88dc8253201545d8098d9f8484cdb967c3629057a1d8ae795922890ee653<td bgcolor=#E8FFFF nowrap>1f8bed5cc1b49df8ad2db514a34314b93644eb20d3aac4f9d1950263f3907f67e39ea9342a09f1c7c58bbbdb5f7d35c4<td bgcolor=#E8FFFF nowrap>D:\auto-unlocker\testing\good\vmwarebase.dll<td bgcolor=#E8FFFF nowrap>07/04/2020 16:55:19<td bgcolor=#E8FFFF nowrap>07/04/2020 16:57:08<td bgcolor=#E8FFFF nowrap>07/04/2020 16:55:19<td bgcolor=#E8FFFF nowrap>7.037.912<td bgcolor=#E8FFFF nowrap>15.5.2 build-15785246<td bgcolor=#E8FFFF nowrap>15.5.2 build-15785246<td bgcolor=#E8FFFF nowrap>3<td bgcolor=#E8FFFF nowrap>dll<td bgcolor=#E8FFFF nowrap>A
<tr><td bgcolor=#FFE8FF nowrap>vmware-vmx.exe<td bgcolor=#FFE8FF nowrap>18b47f8f1575ed0ff1d6eb8489a9c47a<td bgcolor=#FFE8FF nowrap>4cdc2690f831730e2adcb2af4e1783bda6b5372b<td bgcolor=#FFE8FF nowrap>c695d31c<td bgcolor=#FFE8FF nowrap>f5a09140bc7e4d945cb44f5f450b119573ff9cd733daf3ebdb7947c8563c2ed1<td bgcolor=#FFE8FF nowrap>963ad28dc076ab32b01267101fb2a5ce43ed246733310f7fe3c394210edf74e713a9de226ca53fcd566ef8f6126e6515bbd055c4976ffa591775ae66b9e83518<td bgcolor=#FFE8FF nowrap>4bd862f6e337435cb103771baca8508844643139aa3bb262929f660e47921732e9c753b3652d9842a79d96d5e38662d8<td bgcolor=#FFE8FF nowrap>C:\Program Files (x86)\VMware\VMware Player\x64\vmware-vmx.exe<td bgcolor=#FFE8FF nowrap>07/04/2020 17:50:10<td bgcolor=#FFE8FF nowrap>07/03/2020 11:17:04<td bgcolor=#FFE8FF nowrap>07/04/2020 17:50:10<td bgcolor=#FFE8FF nowrap>16.764.376<td bgcolor=#FFE8FF nowrap>15.5.2 build-15785246<td bgcolor=#FFE8FF nowrap>15.5.2 build-15785246<td bgcolor=#FFE8FF nowrap>1<td bgcolor=#FFE8FF nowrap>exe<td bgcolor=#FFE8FF nowrap>A
<tr><td bgcolor=#FFFFE8 nowrap>vmware-vmx-debug.exe<td bgcolor=#FFFFE8 nowrap>cfab05e9b1bd4596f54dd682cba68d5e<td bgcolor=#FFFFE8 nowrap>3701628840b4167b1969d1f60af995cc0b0c7034<td bgcolor=#FFFFE8 nowrap>d8876ee6<td bgcolor=#FFFFE8 nowrap>cf3551659b977063c69ed9499143a7f6b0ccb591720e47b65eca52f628da9b69<td bgcolor=#FFFFE8 nowrap>fd3786bd748ff02409a4b8d8257db6ab6e4854170ccf16ead94bbb0ae37db1d9a0c765c24aa8fa149318aff978f81b7180af8f4f6a1e21789f8c9a80fec02802<td bgcolor=#FFFFE8 nowrap>99e6e6ed4596c97f36891555c089a1fc7fc7aa2d9dbd903d3328ab0bae8192d5afc55aa464c4e29cb6e8c5ee471e072d<td bgcolor=#FFFFE8 nowrap>C:\Program Files (x86)\VMware\VMware Player\x64\vmware-vmx-debug.exe<td bgcolor=#FFFFE8 nowrap>07/04/2020 17:50:10<td bgcolor=#FFFFE8 nowrap>07/03/2020 11:17:00<td bgcolor=#FFFFE8 nowrap>07/04/2020 17:50:10<td bgcolor=#FFFFE8 nowrap>22.104.536<td bgcolor=#FFFFE8 nowrap>15.5.2 build-15785246<td bgcolor=#FFFFE8 nowrap>15.5.2 build-15785246<td bgcolor=#FFFFE8 nowrap>2<td bgcolor=#FFFFE8 nowrap>exe<td bgcolor=#FFFFE8 nowrap>A
<tr><td bgcolor=#E8FFFF nowrap>vmwarebase.dll<td bgcolor=#E8FFFF nowrap>e8bf8ca0bb7e6f1b929ebd2777f33a22<td bgcolor=#E8FFFF nowrap>87818a402b871670f568889c8acadbf731a6ecff<td bgcolor=#E8FFFF nowrap>f73f2fcc<td bgcolor=#E8FFFF nowrap>cead472605eddca069f39157b6812c5cfd5a22e5aad04f905779981c0dfca552<td bgcolor=#E8FFFF nowrap>05f57a26d9bcc5172686693123f7199416891bc4b7de17304afd96309506712bc1ca88dc8253201545d8098d9f8484cdb967c3629057a1d8ae795922890ee653<td bgcolor=#E8FFFF nowrap>1f8bed5cc1b49df8ad2db514a34314b93644eb20d3aac4f9d1950263f3907f67e39ea9342a09f1c7c58bbbdb5f7d35c4<td bgcolor=#E8FFFF nowrap>C:\Program Files (x86)\VMware\VMware Player\vmwarebase.dll<td bgcolor=#E8FFFF nowrap>07/04/2020 17:50:10<td bgcolor=#E8FFFF nowrap>07/03/2020 11:06:18<td bgcolor=#E8FFFF nowrap>07/04/2020 17:50:10<td bgcolor=#E8FFFF nowrap>7.037.912<td bgcolor=#E8FFFF nowrap>15.5.2 build-15785246<td bgcolor=#E8FFFF nowrap>15.5.2 build-15785246<td bgcolor=#E8FFFF nowrap>3<td bgcolor=#E8FFFF nowrap>dll<td bgcolor=#E8FFFF nowrap>A
</table>

The files produced by python and c++ tools are identical, so at least in my case that's not the issue.

If you could remember what kind of procedure you followed before running the working patch it would be useful to identify the problem. 

You can also run the test yourself to give it a bit of reproducibility: copy the python patched files from your install dir (/vmwarebase.dll, /x64/vmware-vmx.exe, /x64/vmware-vmx-debug.exe), uninstall the patch, run the patch with c++ tool and do the same thing, then compare the hashes with some tool ([I use this one](https://www.nirsoft.net/utils/hash_my_files.html)) and post the results here.

**Comment by myusrn** [comment] 2020-04-07 16:59
I made copy of unlocker303\backup folder, ran unlocker303\win-uninstall.cmd, ran auto-unlocker11\Unlocker.exe, compared file size and date of "unlocker303\backup - Copy" and and auto-unlocker11\backup files and they were the same.

I opened vmware 20h1 tech preview 16.0.0 player app and created a new vm and the select a guest operating systems dialog had an "Apple Mac OS X" entry with 10.16 and 10.15 entries in drop down list.

I booted an macOS vm configuration using macOS 10.15.4 installer.iso and that successfully launched me into macOS installer.  I booted an existing macOS vm configuration with macOS 10.15.4 completed installation and it launched and allowed me to login just fine.

Conclusion, issue does not repro.  I must have had some machine specific state in place when i first tested where complete uninstall of existing vmware bits and reinstall clean of new 20h1 tech preview 16.0.0 release then cleared the slate and allowed the auto-unlocker 1.1 to work as expected.  Looking at tech preview release notes it says i should have removed my existing vmware 15.x.x install first before trying 20h1 tech preview install.  Also my 15.5.2 had the auto-unlocker 1.1 patches installed before i did the inplace upgrade to 20h1 tech preview so that could have messed up initial test results.

Apologies for the false alarm.  You can close this issue.

**Comment by paolo-projects** [comment] 2020-04-07 17:17
> I made copy of unlocker303\backup folder, ran unlocker303\win-uninstall.cmd, ran auto-unlocker11\Unlocker.exe, compared file size and date of "unlocker303\backup - Copy" and and auto-unlocker11\backup files and they were the same.
> 

That won't work because the content of the backup folder is the original vmware files, not the patched ones. And moreover the file size is not at all a good way of comparing files equality, especially because the patch doesn't affect the file size.

Anyway if I recall correctly from other issues this is a constant behavior of the patch, the first time you run it it's not working properly but if you run it again it works. At this point I guess it's related to vmware not initializing some registry entries or something along those lines. 

I'll close this issue as it's basically the same behavior of other issues that I'm currently investigating.

**Closed by paolo-projects** 2020-04-07 17:17 UTC
